### ISSUE TITLE
Allow arguments to be passed to program

### ISSUE THREAD

**Issue by MrYakobo** [lchsk/xstarter#65]
Hi! First of all, very nice concept of a program, kudos for building such a clean ui.

I'd like to launch programs with arguments though. Something like `surf google.com` should open [surf](https://surf.suckless.org/) with Google. It feels like wasted potential. Other features such as launching from a specific folder feels more time consuming (should be done in a real terminal) but command line arguments feels like such a hotfix. :fire:

Cheers

**Comment by lchsk** [comment]
Hey @MrYakobo 
Thanks for your message. Passing arguments to an app is a great idea, I'll add it as soon as I can. Cheers :)

**Comment by lchsk** [comment]
@MrYakobo 

This is now done and released in https://github.com/lchsk/xstarter/releases/tag/v0.7.0

> 
>     If the number of search results is equal to 1, you can provide arguments the selected application should be started with, e.g. surf xstarter.org
>     You can provide multiple arguments, e.g. emacs -nw -Q
>     You can select the application you want to provide arguments for by pressing Tab key
>     This feature works both with GUI (press Enter to start) and terminal applications (press C-o to start)
