### ISSUE TITLE
xstarter integration for nnn

### ISSUE THREAD

**Issue by jarun** [lchsk/xstarter#68]
Hi,

Author of [`nnn`](https://github.com/jarun/nnn) here. I was looking for a cool terminal launcher to integrate with `nnn` and `xstarter` looks to be an awesome fit.

I played around with it for a while and there are a few integration points which I believe can be easily addressed so the two utilities play well together.

Please let me know if this sounds like a good idea. Many thanks in advance!

**Comment by jarun** [comment]
I could come up with a POSIX compliant app launcher script that fit my use case.

Thanks anyway!

**Comment by lchsk** [comment]
Hi @jarun 
Thanks, let me know if you have any further ideas!
Cheers

**Comment by jarun** [comment]
Sure thing! Keep up the good work!
