### ISSUE TITLE
Link to homepage not clear

### ISSUE THREAD

**Issue by dalanicolai** [lchsk/xstarter#69]
Hi, I missed the link to the xstarter at the top of the github page and then was wondering where to donwload the .rpm as instructed in the [installation guide](https://github.com/lchsk/xstarter/blob/master/INSTALL.md). Also I could not find the page with google (searching for 'xstarter download' and xstarter rpm').

Then I tried to build xstarter from source but it resulted in some error: 
[build.log](https://github.com/lchsk/xstarter/files/4672016/build.log)

When I came back to github I finally discovered the link to the website at the top. Anyway... maybe you could link to it in the installation guide also, to make it more discoverable.
Thanks for the nice app and emacs interface!

**Comment by lchsk** [comment]
Hi @dalanicolai 
Sorry you had trouble installing it. As to the download links, they're available on github's releases page. But to your point, I'll make sure to update the readmes with current information as they haven't been updated in a while. 

Regarding building it from source - I think that might be because you're trying to build it with the new version of gcc (probably 10) which has introduced quite a few changes. I need to update the source to make it possible to compile with gcc 10 (previous versions of gcc like 8 should work just fine).
Thanks

**Comment by dalanicolai** [comment]
Wauw quick response. I did not know about the github releases page, so thanks I learned something new today. Also I installed version 8.0 for which there is no .rpm, so I used the .zip and it is working already. I just provided the log for your interest. Anyway, I am a happy user now. However I installed it because sometimes I would like to open files in in e.g. nautilus from emacs. I think this might be possible when using helm, but I am using Ivy. Anyway, I will probably provide an ivy interface soon. (Or maybe you know how opening current buffer files is already possible?). Cheers!

**Comment by lchsk** [comment]
Cool, no problem. Not sure to be honest, if I have to do something extra from emacs, I do M-x shell-command, that works for anything :smile:

**Comment by dalanicolai** [comment]
My god, that simple... it is indeed what I was looking for. Of course I
knew about make-process, call-process and start-process, but I was thinking
there must be something even simpler.
I thought someone would have created some solution to choose in which
application to open current file, similar to the function in Spacemacs to
open a file in an external app but uses xdg-open.

```
(defun spacemacs//open-in-external-app (file-path)
  "Open `file-path' in external application."
  (cond
   ((spacemacs/system-is-mswindows)
    (w32-shell-execute "open" (replace-regexp-in-string "/" "\\\\"
file-path)))
   ((spacemacs/system-is-mac) (shell-command (format "open \"%s\""
file-path)))
   ((spacemacs/system-is-linux) (let ((process-connection-type nil))
                                  (start-process "" nil "xdg-open"
file-path)))))
```

So I forgot about shell-command (which is used for the mac in the code
block above). Haha, a little long answer but it felt a little embarrassing.
Well I learned two new things today then. Thanks!
Still, although not very important, an Ivy interface would be nice I guess.
So when I have a spare hour I will look at it.

**Comment by lchsk** [comment]
Released new version that compiles with gcc 10 https://github.com/lchsk/xstarter/releases
Updated docs to include the links to releases
